# Rename this file to languages.toml to enable multilingual support
[zh]
languageName = "汉语"
languagedirection = "ltr"
title = "酱骨头的部落格"
weight = 1
[zh.params.sidebar]
subtitle = "合抱之木，生于毫末；九层之台，起于累土；千里之行，始于足下"

[en]
languageName = "English"
languagedirection = "ltr"
title = "Jack Jiang'Blog"
weight = 2
[en.params.sidebar]
subtitle = "Rome was not built in a day"
