# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Jack Jiang'Blog"
weight = 1

[zh]
languageName = "汉语"
languagedirection = "ltr"
title = "酱骨头的部落格"
weight = 1
